Tortoise/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^turtle_shell/', include('turtle_shell.urls', namespace="turtle_shell")),
    url(r'^phone/', include('phoneFunctions.urls', namespace="phoneFunctions")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phoneFunctions/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.homePage, name = 'homePage'),
]

turtle_shell/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^animal/$', views.animal, name='person'),
    url(r'^fileupload/$', views.get_name, name='get_name'),
    url(r'^thanks/$', views.thanks, name = 'thanks'),
    url(r'^list/$', views.list, name = 'list_animals'),
]

phoneFunctions/models.py
from django.db import models

# Create your models here.

sendSomeEmails/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

turtle_shell/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Animal(models.Model):
    animal_species = models.CharField(max_length=200)
    animal_image = models.ImageField(upload_to='documents', null=True)
    
    def __str__(self):
        return self.animal_species

turtle_shell/forms.py
from django import forms
from django.forms import ModelForm
from .models import Animal

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)
    
#class AnimalForm(forms.Form):
#    animal_species = forms.CharField(max_length=100)
#    image = forms.ImageField()
#    email = forms.EmailField()

class AnimalForm(ModelForm):
    class Meta:
        model = Animal
        fields = ['animal_species', 'animal_image']

phoneFunctions/views.py
from django.shortcuts import render

# Create your views here.
def homePage(request):
    return render(request, 'phoneFunctions/homePage.html')

sendSomeEmails/views.py
from django.shortcuts import render

# Create your views here.

turtle_shell/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .forms import NameForm, ContactForm, AnimalForm
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from .models import Animal


def index(request):
    return render(request, 'turtle_shell/index_page.html')
    #return HttpResponse("Hello, world. You're at the turtle_shell index.")
    
def animal(request):
    return render(request, 'turtle_shell/people_index.html')

def list(request):
    return render(request, 'turtle_shell/list.html', {'animals':Animal.objects.all()})
    
def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AnimalForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            newAnimal = Animal(animal_species = request.POST['animal_species'], animal_image = request.FILES['animal_image'])
            newAnimal.save()
            return HttpResponseRedirect(reverse('turtle_shell:list_animals'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = AnimalForm()

    return render(request, 'turtle_shell/name.html', {'form': form})
    
def thanks(request):
    return HttpResponse("Thank you. Your form has been submitted.")

phoneFunctions/templates/phoneFunctions/homePage.html
<!DOCTYPE html>
<html>
	<head>
		Phone app main page
	</head>
	<body>
	<h3>
		<a href="{% url 'turtle_shell:index' %}">Go to the turtle shell app homepage
	</h3>
	</body>
</html>

turtle_shell/templates/turtle_shell/index_page.html
<!DOCTYPE html>
<html>
	<head>
		Turtle shell app main page
	</head>
	
	<body>
		<h3>
			<a href="{% url 'phoneFunctions:homePage' %}">Go to the phoneFunctions app homepage
		</h3>
	</body>
</html>

turtle_shell/templates/turtle_shell/list.html
<head>
	animal list
</head>

<body>
	<!-- List of uploaded animals -->
	{% if animals %}
		{% for animal in animals %}
			<li>{{animal.animal_species}}</li>
			{% if animal.animal_image %}
				<li><a href="{{ animal.animal_image.url }}">{{ animal.animal_image.name}}
			{% endif %}
		{% endfor %}
	{% else %}
		<p>No images.</p>
	{% endif %}
</body>

turtle_shell/templates/turtle_shell/name.html
<form action= "{% url 'turtle_shell:get_name' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Animal Species: {{ form.animal_species }}</h1>
	<h1>Image: {{form.animal_image}}</h1>
    <input type="submit" value="Submit" />
</form>

turtle_shell/templates/turtle_shell/people_index.html
<form action="/your_name/" method="post">
    <label for="your_name">Your name: </label>
    <input id="your_name" type="password" name="your_name" value="{{ current_name }}">
    <input type="file" value="OK">
	Month<input type="month">
	Color<input type = "color" value="#00FF00">
	<input type="submit" value="Submit">
</form>